Deep Learning with PyTorch A 60 Minute Blitz

In [1]:
from __future__ import print_function
import torch

x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  1.0842e-19, -1.2472e-27],
        [ 4.6577e-10,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  4.9102e-34,  1.4013e-45],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00]])


In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1002, 0.7185, 0.2078],
        [0.9008, 0.3965, 0.4144],
        [0.5663, 0.2216, 0.0890],
        [0.6127, 0.5090, 0.6936],
        [0.3121, 0.5371, 0.3155]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 重载 dtype!
print(x)  

print(x.size()) #torch.Size本质上还是tuple，所以支持tuple的一切操作


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7981,  0.2493, -0.7194],
        [ 0.3679,  1.2780, -2.2528],
        [-0.2227,  0.2879,  0.4972],
        [-0.5812, -0.4504,  0.5923],
        [ 0.5480, -0.2582, -0.1864]])
torch.Size([5, 3])


# 运算

In [10]:
y = torch.rand(5, 3)
print(x + y) # first way

print(torch.add(x, y)) # second way 

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result) # third way 

# adds x to y fourth way 
y.add_(x)
print(y)

# 注意： 任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x

tensor([[-0.3770,  0.6977,  0.0774],
        [ 0.9525,  2.0335, -2.1073],
        [-0.1558,  1.0540,  1.0401],
        [-0.2023, -0.2495,  1.5115],
        [ 0.8604,  0.2533,  0.7508]])
tensor([[-0.3770,  0.6977,  0.0774],
        [ 0.9525,  2.0335, -2.1073],
        [-0.1558,  1.0540,  1.0401],
        [-0.2023, -0.2495,  1.5115],
        [ 0.8604,  0.2533,  0.7508]])
tensor([[-0.3770,  0.6977,  0.0774],
        [ 0.9525,  2.0335, -2.1073],
        [-0.1558,  1.0540,  1.0401],
        [-0.2023, -0.2495,  1.5115],
        [ 0.8604,  0.2533,  0.7508]])
tensor([[-0.3770,  0.6977,  0.0774],
        [ 0.9525,  2.0335, -2.1073],
        [-0.1558,  1.0540,  1.0401],
        [-0.2023, -0.2495,  1.5115],
        [ 0.8604,  0.2533,  0.7508]])
